name: Publish Python Package to PyPI ${{ github.event.inputs.version }}

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Override the release version number (e.g. 8.0.0a5)"
        default: 0.0.0a1

jobs:
  deploy-pypi:
    name: PyPI deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Choose the Python version you need
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine readme_renderer[md]
      - name: Validate README for PyPI
        run: |
          python -m readme_renderer README.md -o /tmp/README.html    
      - name: Build package
        run: |
          sed -i 's/RELEASE_VERSION/${{ github.event.inputs.version }}/' setup.cfg
          python -m build
      - name: Check distribution files
        run: twine check dist/*
      - name: Publish to PyPI
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__  # Use API token
          password: ${{ secrets.PYPI_API_TOKEN }}
